'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { FormInput } from '@/components/ui/FormInput';
import { toast } from 'sonner';
import { PawPrint, User, Mail, Phone, MapPin, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

interface RegistrationFormData {
  // Owner details
  ownerName: string;
  ownerEmail: string;
  ownerPhone: string;
  ownerAddress: string;
  password: string;
  confirmPassword: string;

  // Pet details
  petName: string;
  species: string;
  breed: string;
  birthDate: string;
  age: string;
}

export default function RegisterPetPage() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formData, setFormData] = useState<RegistrationFormData>({
    ownerName: '',
    ownerEmail: '',
    ownerPhone: '',
    ownerAddress: '',
    password: '',
    confirmPassword: '',
    petName: '',
    species: '',
    breed: '',
    birthDate: '',
    age: '',
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    
    // If birthDate is changed, auto-calculate age
    if (name === 'birthDate') {
      setFormData(prev => ({
        ...prev,
        birthDate: value,
        age: calculateAge(value)
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: value
      }));
    }
  };

  const validate = (): string[] => {
    const issues: string[] = [];

    // Owner validation
    if (!formData.ownerName.trim()) issues.push('Owner name is required');
    if (!formData.ownerEmail.trim()) issues.push('Email is required');
    if (!formData.ownerPhone.trim()) issues.push('Phone number is required');
    if (!formData.ownerAddress.trim()) issues.push('Address is required');

    // Password validation
    if (!formData.password) issues.push('Password is required');
    if (formData.password.length < 8) issues.push('Password must be at least 8 characters');
    if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])/.test(formData.password)) {
      issues.push('Password must contain uppercase, lowercase, number, and special character');
    }
    if (formData.password !== formData.confirmPassword) issues.push('Passwords do not match');

    // Pet validation
    if (!formData.petName.trim()) issues.push('Pet name is required');
    if (!formData.species) issues.push('Species is required');
    if (!formData.breed.trim()) issues.push('Breed is required');

    return issues;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    const issues = validate();
    if (issues.length) {
      setError(issues.join('\n'));
      setIsSubmitting(false);
      return;
    }

    try {
      const res = await fetch('/api/register-pet', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || 'Registration failed');
      }

      const result = await res.json();

      toast.success('Registration successful! QR code will be sent to your email once generated by admin.');
      
      // Redirect to success page or landing page
      setTimeout(() => {
        router.push('/');
      }, 2000);

    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Registration failed';
      setError(errorMessage);
      toast.error(`❌ ${errorMessage}`);
      console.error('Registration error:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

// Helper function to calculate age in years and months
function calculateAge(birthDate: string): string {
  if (!birthDate) return '';
  
  const birth = new Date(birthDate);
  const today = new Date();
  
  let years = today.getFullYear() - birth.getFullYear();
  let months = today.getMonth() - birth.getMonth();
  
  // Adjust if birth month hasn't occurred yet this year
  if (months < 0) {
    years--;
    months += 12;
  }
  
  // Adjust if birth day hasn't occurred yet this month
  if (today.getDate() < birth.getDate()) {
    months--;
    if (months < 0) {
      years--;
      months += 12;
    }
  }
  
  // Format the result
  if (years === 0 && months === 0) return 'Less than 1 month';
  if (years === 0) return `${months} month${months > 1 ? 's' : ''}`;
  if (months === 0) return `${years} year${years > 1 ? 's' : ''}`;
  return `${years} year${years > 1 ? 's' : ''}, ${months} month${months > 1 ? 's' : ''}`;
}

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                <span className="text-white text-xl">🐾</span>
              </div>
              <span className="text-xl font-semibold">PetCare Clinic</span>
            </div>
            <Link href="/">
              <Button variant="secondary" className="flex items-center gap-2">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6 text-center">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="w-16 h-16 rounded-lg bg-blue-600 text-white flex items-center justify-center">
              <PawPrint className="w-9 h-9" />
            </div>
          </div>
          <h1 className="text-3xl font-bold mb-2">Register Your Pet</h1>
          <p className="text-gray-600">
            Register your pet and create your account. You'll receive a QR code via email to access medical records.
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          {error && (
            <div className="mb-6 rounded-md bg-red-50 border border-red-200 p-4 text-sm text-red-700 whitespace-pre-line">
              {error}
            </div>
          )}

          {/* Owner Information */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4 text-green-600">
              <User className="w-6 h-6" />
              <h3 className="text-xl font-semibold">Your Information</h3>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <FormInput
                label="Full Name"
                name="ownerName"
                value={formData.ownerName}
                onChange={handleChange}
                placeholder="e.g., John Smith"
                required
              />

              <FormInput
                label="Email"
                name="ownerEmail"
                type="email"
                value={formData.ownerEmail}
                onChange={handleChange}
                placeholder="e.g., john@example.com"
                required
              />

              <FormInput
                label="Phone Number"
                name="ownerPhone"
                type="tel"
                value={formData.ownerPhone}
                onChange={handleChange}
                placeholder="e.g., +62 812 3456 7890"
                required
              />

              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Address <span className="text-red-500">*</span>
                </label>
                <textarea
                  name="ownerAddress"
                  value={formData.ownerAddress}
                  onChange={handleChange}
                  required
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter your complete address"
                />
              </div>

              <FormInput
                label="Password"
                name="password"
                type="password"
                value={formData.password}
                onChange={handleChange}
                placeholder="Min. 8 characters"
                required
              />

              <FormInput
                label="Confirm Password"
                name="confirmPassword"
                type="password"
                value={formData.confirmPassword}
                onChange={handleChange}
                placeholder="Re-enter password"
                required
              />
            </div>

            <div className="mt-4 p-3 bg-blue-50 rounded-lg text-sm text-blue-800">
              <strong>Password Requirements:</strong> Minimum 8 characters, must include uppercase, lowercase, number, and special character
            </div>
          </Card>

          {/* Pet Information */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4 text-blue-600">
              <PawPrint className="w-6 h-6" />
              <h3 className="text-xl font-semibold">Pet Details</h3>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <FormInput
                label="Pet Name"
                name="petName"
                value={formData.petName}
                onChange={handleChange}
                placeholder="e.g., Max, Luna"
                required
              />

              <div className="space-y-1">
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Species <span className="text-red-500">*</span>
                </label>
                <select
                  name="species"
                  value={formData.species}
                  onChange={handleChange}
                  required
                  title="Select species"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="">Select species</option>
                  <option value="dog">Dog</option>
                  <option value="cat">Cat</option>
                  <option value="bird">Bird</option>
                  <option value="rabbit">Rabbit</option>
                  <option value="other">Other</option>
                </select>
              </div>

              <FormInput
                label="Breed"
                name="breed"
                value={formData.breed}
                onChange={handleChange}
                placeholder="e.g., Golden Retriever, Persian"
                required
              />

              <FormInput
                label="Birth Date"
                name="birthDate"
                type="date"
                value={formData.birthDate}
                onChange={handleChange}
                required
              />

              <FormInput
                label="Age (auto-calculated)"
                name="age"
                type="text"
                value={formData.age}
                onChange={handleChange}
                placeholder="Will be calculated from birth date"
                readOnly
                disabled
              />
            </div>

            <div className="mt-4 p-3 bg-yellow-50 rounded-lg text-sm text-yellow-800">
              <strong>Note:</strong> Pet weight will be measured by our medical team during the first visit.
            </div>
          </Card>

          {/* Submit Button */}
          <div className="flex gap-3">
            <Button
              type="submit"
              variant="primary"
              disabled={isSubmitting}
              className="flex-1"
            >
              {isSubmitting ? 'Registering...' : 'Register My Pet'}
            </Button>
            {/* <Link href="/" className="flex-1">
              <Button type="button" variant="secondary" className="w-full">
                Cancel
              </Button>
            </Link> */}
          </div>
        </form>
      </div>
    </div>
  );
}